### PR TITLE
Use markdown in README

### PR DESCRIPTION
**Pull request by SuicSoft**
This will make the project README easier to read

### CODE REVIEW

**Comment by palinek** [comment]
GTM

**Comment by SuicSoft** [comment]
@palinek What do you mean?

**Comment by palinek** [comment]
Good To Merge... meaning I'm OK with the changes

**Comment by SuicSoft** [comment]
@palinek OK

**Comment by pmattern** [comment]
While at it you could eventually 'An' with 'A' in "An Qt implementation..." because that's grammatically wrong, AFAIK.

Other than that GTM from my side, too.

**Comment by SuicSoft** [comment]
@jleclanche I have fixed the error @pmattern said

**Comment by jleclanche** [comment]
I have already landed it, you can file another PR if you like.

**Comment by SuicSoft** [comment]
I have to be an collaborator to edit it

**Comment by SuicSoft** [comment]
OK , I created a PR

**Pull request merged**
