### PR TITLE
Strings

### PR DESCRIPTION
**Pull request by luis-pereira**

### CODE REVIEW

**Comment by palinek** [comment]
Just briefly reviewed the changes.... I'm trusting your judgement -> GTM

**Comment by luis-pereira** [comment]
@palinek amended changes 

``` diff
diff --git a/qtxdg/xdgdesktopfile.cpp b/qtxdg/xdgdesktopfile.cpp
index 659fbf4..b7ad0be 100644
--- a/qtxdg/xdgdesktopfile.cpp
+++ b/qtxdg/xdgdesktopfile.cpp
@@ -676,13 +676,13 @@ void XdgDesktopFile::setLocalizedValue(const QString &key, const QVariant &value
  ************************************************/
 QString XdgDesktopFile::localizedKey(const QString& key) const
 {
-    QString lang = QString::fromLocal8Bit(qgetenv("LC_MESSAGES"));
+    QString lang = QString::fromLatin1(qgetenv("LC_MESSAGES"));
 
     if (lang.isEmpty())
-        lang = QString::fromLocal8Bit(qgetenv("LC_ALL"));
+        lang = QString::fromLatin1(qgetenv("LC_ALL"));
 
     if (lang.isEmpty())
-         lang = QString::fromLocal8Bit(qgetenv("LANG"));
+         lang = QString::fromLatin1(qgetenv("LANG"));
 
     QString modifier = lang.section(QLatin1Char('@'), 1);
     if (!modifier.isEmpty())
@@ -929,7 +929,7 @@ QString expandEnvVariables(const QString str)
     res.replace(QRegExp(QString::fromLatin1("~(?=$|/)")), QFile::decodeName(qgetenv("HOME")));
 
     replaceVar(res, QLatin1String("HOME"), QFile::decodeName(qgetenv("HOME")));
-    replaceVar(res, QLatin1String("USER"), QString::fromLocal8Bit(getenv("USER")));
+    replaceVar(res, QLatin1String("USER"), QString::fromUtf8(getenv("USER")));
 
     replaceVar(res, QLatin1String("XDG_DESKTOP_DIR"),   XdgDirs::userDir(XdgDirs::Desktop));
     replaceVar(res, QLatin1String("XDG_TEMPLATES_DIR"), XdgDirs::userDir(XdgDirs::Templates));
```

**Comment by palinek** [comment]
```diff
-    replaceVar(res, QLatin1String("USER"), QString::fromLocal8Bit(getenv("USER")));
+    replaceVar(res, QLatin1String("USER"), QString::fromUtf8(getenv("USER")));
```
1. why not using the `qgetenv`?
2. does the USER env var need to be encoded in UTF-8? Isn't it locale dependent? (sorry if the question is stupid, but I'm not much aware of this area)

**Comment by luis-pereira** [comment]
@palinek 
1. That was a typo. Thanks :+1: 
2. I wasn't aware that `QTextCodec::codecForLocale()` fallback to `QIconvCodec` when no builtin codec for the locale can be found.

Very good questions indeed.

Production quality, now, IMO

``` diff
diff --git a/qtxdg/xdgdesktopfile.cpp b/qtxdg/xdgdesktopfile.cpp
index b7ad0be..7c6f132 100644
--- a/qtxdg/xdgdesktopfile.cpp
+++ b/qtxdg/xdgdesktopfile.cpp
@@ -486,7 +486,7 @@ bool XdgDesktopFileData::startByDBus(const QStringList& urls) const
     path = path.replace(QLatin1Char('.'), QLatin1Char('/')).prepend(QLatin1Char('/'));
 
     QVariantMap platformData;
-    platformData.insert(QLatin1String("desktop-startup-id"), QString::fromUtf8(qgetenv("DESKTOP_STARTUP_ID")));
+    platformData.insert(QLatin1String("desktop-startup-id"), QString::fromLocal8Bit(qgetenv("DESKTOP_STARTUP_ID")));
 
     QDBusObjectPath d_path(path);
     if (d_path.path().isEmpty())
@@ -676,13 +676,13 @@ void XdgDesktopFile::setLocalizedValue(const QString &key, const QVariant &value
  ************************************************/
 QString XdgDesktopFile::localizedKey(const QString& key) const
 {
-    QString lang = QString::fromLatin1(qgetenv("LC_MESSAGES"));
+    QString lang = QString::fromLocal8Bit(qgetenv("LC_MESSAGES"));
 
     if (lang.isEmpty())
-        lang = QString::fromLatin1(qgetenv("LC_ALL"));
+        lang = QString::fromfromLocal8Bit(qgetenv("LC_ALL"));
 
     if (lang.isEmpty())
-         lang = QString::fromLatin1(qgetenv("LANG"));
+         lang = QString::fromLocal8Bit(qgetenv("LANG"));
 
     QString modifier = lang.section(QLatin1Char('@'), 1);
     if (!modifier.isEmpty())
@@ -929,7 +929,7 @@ QString expandEnvVariables(const QString str)
     res.replace(QRegExp(QString::fromLatin1("~(?=$|/)")), QFile::decodeName(qgetenv("HOME")));
 
     replaceVar(res, QLatin1String("HOME"), QFile::decodeName(qgetenv("HOME")));
-    replaceVar(res, QLatin1String("USER"), QString::fromUtf8(getenv("USER")));
+    replaceVar(res, QLatin1String("USER"), QString::fromLocal8Bit(qgetenv("USER")));
 
     replaceVar(res, QLatin1String("XDG_DESKTOP_DIR"),   XdgDirs::userDir(XdgDirs::Desktop));
     replaceVar(res, QLatin1String("XDG_TEMPLATES_DIR"), XdgDirs::userDir(XdgDirs::Templates));
@@ -1072,7 +1072,7 @@ bool checkTryExec(const QString& progName)
     if (progName.startsWith(QDir::separator()))
         return QFileInfo(progName).isExecutable();
 
-    QStringList dirs = QString::fromLocal8Bit(qgetenv("PATH")).split(QLatin1Char(':'));
+    QStringList dirs = QFile::decodeName(qgetenv("PATH")).split(QLatin1Char(':'));
 
     foreach (const QString &dir, dirs)
     {
diff --git a/qtxdg/xdgmenuapplinkprocessor.cpp b/qtxdg/xdgmenuapplinkprocessor.cpp
index 2a7d148..f031940 100644
--- a/qtxdg/xdgmenuapplinkprocessor.cpp
+++ b/qtxdg/xdgmenuapplinkprocessor.cpp
@@ -240,7 +240,7 @@ bool XdgMenuApplinkProcessor::checkTryExec(const QString& progName)
     if (progName.startsWith(QDir::separator()))
         return QFileInfo(progName).isExecutable();
 
-    const QStringList dirs = QString::fromLocal8Bit(qgetenv("PATH")).split(QLatin1Char(':'));
+    const QStringList dirs = QFile::decodeName(qgetenv("PATH")).split(QLatin1Char(':'));
 
     foreach (const QString &dir, dirs)
     {
```

**Comment by palinek** [comment]
Seems good, again :)

... so name of the `QString::fromLocal8Bit` function is a bit misleading and it properly decodes also from multi-byte locale?

**Comment by luis-pereira** [comment]
@palinek as a fallback, when compiled with iconv support.

**Comment by palinek** [comment]
> as a fallback, when compiled with iconv support.

OK

**Comment by luis-pereira** [comment]
It's time to merge it.

**Pull request merged**
