### PR TITLE
Fix missing slash in paths in xdgDirList

### PR DESCRIPTION
**Pull request by paulolieuthier**
Fixes lxde/lxqt#518.

### CODE REVIEW

**Comment by jleclanche** [comment]
hold

**Comment by palinek** [comment]
Just looked quickly at the ```xdgdirs.cpp``` and there are path fiddlings by hand all around. Is there a reason to not do it in portable way... e.g. using ```boost::filesystem::path``` (http://www.boost.org/doc/libs/1_57_0/libs/filesystem/doc/reference.html#class-path)

**Comment by jleclanche** [comment]
@palinek I was saying on IRC that we should be using QDir::cleanPath() or some such.

We don't depend on boost right now btw, and we won't.

**Comment by paulolieuthier** [comment]
The hard-coded paths are standard paths according to the xdg spec. No problem with that.  I think the patch is appropriate because `XdgDirs::dataDirs()` must return valid complete paths. Using `QDir::cleanPath()` would remove the ending slash of the paths that already have it and we would have to append the slash anyway. I'm just checking if there is an ending slash and appending one if there is not.

**Comment by luis-pereira** [comment]
```QDir::cleanPath()``` doesn't solve this issue. It's ending slash behaviour is not specified so we must not rely on that. I'm not against using ```QDir::cleanPath()``` tough. 
@paulolieuthier may I push onto this branch ?

**Comment by jleclanche** [comment]
What about `QDir::canonicalPath`?

**Comment by paulolieuthier** [comment]
@luis-pereira I tested `QDir::cleanPath` and it removes the ending slash. Please, feel free to work on this branch.

**Comment by luis-pereira** [comment]
@paulolieuthier I know that it does that. But it's a not documented behaviour.

**Comment by jleclanche** [comment]
I'd rather rely on undocumented but proven behaviour than an internal hack :)

**Comment by paulolieuthier** [comment]
I'm in favour of whatever you guys decide, I just want to see the bug fixed :smile:. But it doesn't look like a hack to me, we're just adding a slash if there is not one.

**Comment by luis-pereira** [comment]
I wouldn't also call this patch a hack. It appends an trailing / ```QDir::cleanPath()``` does the opposite in an undocumented way. QFileSystemWatcher also worked fine in an undocumented way, until it got changed. 
@paulolieuthier @jleclanche Updated.

**Comment by paulolieuthier** [comment]
Much better. GTM

**Comment by jleclanche** [comment]
Alright, gtm. Squash and ship please.

**Pull request merged**
