### PR TITLE
desktopfile: support for DBusActivatable applications

### PR DESCRIPTION
**Pull request by palinek**
Trying to implement lxde/lxqt#47...
The spec I followed: http://standards.freedesktop.org/desktop-entry-spec/desktop-entry-spec-latest.html

This is only the first shot. Issues:
- `CMakeLists.txt`
  - are the DBUS requirements correct?
  - i was completely ignoring qt4 section
- Desktop Actions are not handled for DBusActivatable... are they handled in the standard way?
- `platform_data` parameter is not handled

@paulolieuthier, @luis-pereira, @PCMan, @jleclanche 
This needs good review and support from you, guys. Will appreciate all comments and suggestions for the mentioned issues (or any others that you see).

### CODE REVIEW

**Comment by jleclanche** [comment]
Looks good!

**Comment by palinek** [comment]
@jleclanche from the diff it seems that it was done in half an hour.... but i was completely lost in the whole DBus handling :(

**Comment by luis-pereira** [comment]
@palinek I'm testing it also.

**Comment by luis-pereira** [comment]
@palinek Consider this changes: https://github.com/lxde/libqtxdg/tree/extend-dbus_act
TODO: Desktop Actions. I have to re-read the standard.

**Comment by palinek** [comment]
@luis-pereira if you wish you can push your enhancements into my fork (just added you as colaborator) and merge this PR

**Comment by luis-pereira** [comment]
Closed by 21c4907b9abb62ecfeb289754e48d5e2d203d239. Closes #52 
Rebased before the push.
@palinek Thanks :+1:

**Pull request closed without merging**
