### PR TITLE
xdgdesktopfile: Actions handling

### PR DESCRIPTION
**Pull request by palinek**
This is for lxde/lxqt#1319

### CODE REVIEW

**Comment by luis-pereira** [comment]
@palinek I will be away one more week.If you and @tsujan think it's ready. Go ahead.

**Comment by agaida** [comment]
GTM - but the change introduce some new symbols. Lucky us, the resulting libqtxdg stays backward compatible - only additional symbols. So we must release 0.4.1 if we want to have this in the upcoming release.

```diff

  (c++)"XdgMimeType::~XdgMimeType()@Base" 1.0.0
+ _ZNK14XdgDesktopFile10actionIconERK7QStringRK5QIcon@Base 3.0.0-2
+ _ZNK14XdgDesktopFile10actionNameERK7QString@Base 3.0.0-2
+ _ZNK14XdgDesktopFile14actionActivateERK7QStringRK11QStringList@Base 3.0.0-2
+ _ZNK14XdgDesktopFile14actionIconNameERK7QString@Base 3.0.0-2
+ _ZNK14XdgDesktopFile7actionsEv@Base 3.0.0-2
  (c++)"non-virtual thunk to XdgMenuWidget::~XdgMenuWidget()@Base" 1.0.0
```

**Comment by palinek** [comment]
> the change introduce some new symbols. Lucky us, the resulting libqtxdg stays backward compatible

...nothing to do with luck. It was done backward compatible intentinally.

**Comment by agaida** [comment]
:) - but we must issue a point release

**Pull request merged**
