### PR TITLE
Fix readme 2

### PR DESCRIPTION
**Pull request by SuicSoft**

### CODE REVIEW

**Comment by pmattern** [comment]
Please exchange the commit message with something more meaningful.
We actually go for commit messages as e. g. described in http://chris.beams.io/posts/git-commit/ (just as a hint - I'm aware you're normally writing commit messages similar to this already).

**Comment by SuicSoft** [comment]
How do I edit the commit message using the web UI. I can't use `git` (although I have done this before) because my PC is having problems and I am using Android now

**Comment by pmattern** [comment]
No clue, tbh.
Would you eventually be fine with me doing it on behalf of you? Of course I would do it in a way preserving your authorship.

**Comment by SuicSoft** [comment]
Ok

**Comment by pmattern** [comment]
Landed in 8b6bba2. Thanks.

**Pull request closed without merging**
