### PR TITLE
Remove cpack

### PR DESCRIPTION
**Pull request by agaida**
We will not use it anymore

### CODE REVIEW

**Comment by agaida** [comment]
@luis-pereira @palinek @paulolieuthier @jleclanche @pmattern - what do you think? - With .gitattributes we can use git archive without problems and don't have the export code in CMakeLists.txt lxqt-wide

**Comment by jleclanche** [comment]
I doN't think it was ever really useful, tbh.

**Comment by luis-pereira** [comment]
@agaida You know better than me. If you think it's better, go ahead.

**Comment by paulolieuthier** [comment]
Pull the trigger.

**Comment by palinek** [comment]
I'm also out of the discussion because lack of knowledge...

**Pull request merged**
