### PR TITLE
XdgDesktopFile: Adds Exec fallback when DBusActivatable fails

### PR DESCRIPTION
**Pull request by luis-pereira**
We fallback to use the Exec key when the DBusActivatable fails.
Closes lxde/lxqt#967.

### CODE REVIEW

**Comment by jleclanche** [comment]
gtm

**Comment by palinek** [comment]
I was also considering this, but it violates the specification "If the value is true then implementations should ignore the Exec key and send a D-Bus message to launch the application."

**Comment by luis-pereira** [comment]
@palinek But the specification also says:

>  Even if DBusActivatable is true, Exec should be specified for compatibility with implementations that do not understand DBusActivatable.

**Comment by palinek** [comment]
> that do not understand DBusActivatable

But we do.

**Comment by luis-pereira** [comment]
Yes. But how do libqtxdg determine if a given environment understands or not  `DBusActivatable` ?

**Comment by palinek** [comment]
> Yes. But how do libqtxdg determine if a given environment understands or not DBusActivatable ?

Libqtxdg is the environment/implementation here, not?

**Comment by luis-pereira** [comment]
Sure. Not exactly what I meant.
What I meant is that even the standard guys do not entirely follow the standard.
When `DBusActivatable` was introduced at least desktop-file-validate should got update to warn about the presence of `-` in the filename.

We strictly follow the standard and get a fail (user viewpoint).

**Comment by palinek** [comment]
> We strictly follow the standard and get a fail (user viewpoint).

From user point of view it is definitely better to try the `Exec` as a fallback if `DBus` fails... there is no doubt.

Let's do it. But IMO it has to be documented somehow (comment in code, readme?), that we are violating the standard for a good reason.

**Comment by luis-pereira** [comment]
@palinek I do agree with the documentation). Will write it.

**Comment by luis-pereira** [comment]
@palinek Documented at https://github.com/lxde/libqtxdg/pull/80/commits/d019654dc3d83f7986f8272c5ae39650364b532d. Take a look.

**Comment by palinek** [comment]
It's a bit too verbose... But the fallback executed only for whatever "fail" reason (no dbus at all, not properly configured the dbus service for the applicaion...), not only the invalid name.

**Comment by luis-pereira** [comment]
@palinek It's verbose, but IMO it deserves a very good explanation.
The fallback is now only executed when there is an invalid dbus object path.

**Comment by palinek** [comment]
> The fallback is now only executed when there is an invalid dbus object path.

Hm... why? From end user POI it doesn't matter what triggered the error. With my previous note I proposed a change in comment/doc, not the change of the previous logic.

**Comment by luis-pereira** [comment]
@palinek I inferred from your word that you only agreed in doing it in that special casw

**Comment by palinek** [comment]
> that you only agreed in doing it in that special case

Sorry for confusing you :smile:

**Comment by luis-pereira** [comment]
@palinek No problem. Updated.

**Comment by paulolieuthier** [comment]
GTM.

**Comment by palinek** [comment]
GTM

**Pull request merged**
