### PR TITLE
It adds loadIcon() timing measurements.

### PR DESCRIPTION
**Pull request by luis-pereira**
It adds an per icon load time and a Total loadIcon() timing info.

### CODE REVIEW

**Comment by agaida** [comment]
I guess that should only be temporary? If not i would suggest to make the debugging thing optional.

**Comment by luis-pereira** [comment]
@agaida Timing is a important issue here. It's permanent. `qtxdg-iconfinder` is in it's essence but I can make optional.

**Comment by palinek** [comment]
IMO it doesn't need to be optional. The qtxdg-iconfinder is developer/debug tool.

**Comment by agaida** [comment]
so i'm ok with

**Pull request merged**
