### PR TITLE
Xdgiconloader

### PR DESCRIPTION
**Pull request by luis-pereira**

### CODE REVIEW

**Comment by agaida** [comment]
Hi, 
looks good and make sense - some questions:
```
usr/share/cmake/qt5xdg/qt5xdg-config.cmake
usr/share/cmake/qt5xdg/qt5xdg-config-version.cmake - do we need something like that for the iconloader
usr/share/cmake/qt5xdg/qt5xdg-targets.cmake
usr/share/cmake/qt5xdg/qt5xdg-targets-none.cmake

usr/lib/x86_64-linux-gnu/pkgconfig/Qt5Xdg.pc - do we need a .pc file for the icon loader?
```

**Comment by palinek** [comment]
> usr/lib/x86_64-linux-gnu/pkgconfig/Qt5Xdg.pc - do we need a .pc file for the icon loader?

Why shouldn't we provide it for (possible) autotool usage?

**Comment by luis-pereira** [comment]
@agaida qt5xdg-xxxxxxxxxx.cmake are common to all the libraries within the qt5xdg package.
@palinek @agaida Yes, .pc for the XdgIconLoader will be provided. That's part of the reasons it is still a WIP.

**Comment by luis-pereira** [comment]
@agaida @palinek Give it a try.

**Comment by palinek** [comment]
Compiled/used libqt5xdg(#84) + lxqt-qtplugin(lxde/lxqt-qtplugin#10) and it is working as expected (the new icon loader engine is used). With the applied fix (assuming that this is the only needed change from lxde/lxqt-qtplugin#9):
```diff
diff --git a/xdgiconloader/xdgiconloader.cpp b/xdgiconloader/xdgiconloader.cpp
index 98adaa4..1106a20 100644
--- a/xdgiconloader/xdgiconloader.cpp
+++ b/xdgiconloader/xdgiconloader.cpp
@@ -503,7 +503,7 @@ static bool directoryMatchesSize(const XdgIconDirInfo &dir, int iconsize)
         return dir.size == iconsize;
 
     } else if (dir.type == XdgIconDirInfo::Scalable) {
-        return dir.size <= dir.maxSize &&
+        return dir.size >= dir.maxSize &&
                 iconsize >= dir.minSize;
 
     } else if (dir.type == XdgIconDirInfo::Threshold) {
```
..also the problem with breeze(lxde/lxqt#1048) is fixed:

screenshot

Note: this is preview w/o the iconloader fix:
screenshot


All in all... Good Job!

GTM

**Comment by agaida** [comment]
GTM - go for it

**Comment by paulolieuthier** [comment]
GTM.

**Pull request merged**
