### PR TITLE
Backport QIcon-related Qt fixes

### PR DESCRIPTION
**Pull request by paulolieuthier**

### CODE REVIEW

**Comment by paulolieuthier** [comment]
@luis-pereira is this mergeable?

**Comment by luis-pereira** [comment]
@paulolieuthier Yes it is.

**Comment by paulolieuthier** [comment]
GTM.

**Comment by luis-pereira** [comment]
It must also land on master. I've been testing for a week now. Working without problems.
Does anyone have any feedback ?

**Comment by tsujan** [comment]
GTM.

**Pull request merged**
