### PR TITLE
desktopfile: run new process as a direct child

### PR DESCRIPTION
**Pull request by palinek**
fixes lxde/libqtxdg#50

### CODE REVIEW

**Comment by luis-pereira** [comment]
@palinek Great work. But this means that every app won't be detached. IMO we have to make a compromise here and create a list of non detach execs,

**Comment by palinek** [comment]
@luis-pereira why is detaching so critical?

**Comment by PCMan** [comment]
If not detached, a new process will become a child of the process which
calls the API.
Then when the parent process, for example lxqt-panel, is killed, all of the
apps launched by it will be killed as well, which is not we want.
So, the new processes should be detached.
2015/3/18 下午3:01 於 "palinek" <notifications@github.com> 寫道：

**Comment by palinek** [comment]
@PCMan that's what I thought also... but that's truth only in case the parent is a session leader and has attached terminal .. see my "selfdiscussion" in lxde/libqtxdg#50

**Comment by luis-pereira** [comment]
@palinek You are totally right in your self discussion.
The case where the parent has an attached terminal is important for developers (at least). Most of the times, during debugging and testing, developers launch the panel (for example) from a terminal. In that case killing the terminal will also kill any panel launched apps. I'm not looking forward to that.

@palinek @PCMan  Here's a draft of my proposal, based on @palinek work: https://github.com/lxde/libqtxdg/tree/add-nondetach-exec-list

**Comment by palinek** [comment]
@luis-pereira the decision is up to you. But your solution does not handle e.g `Exec=/usr/bin/pkexec foo`, the check should be probably done only on the basename

**Comment by luis-pereira** [comment]
@palinek It does indeed handle it. ```QString::contains()``` does it. If we check only the basename (command) we miss something like this: ```Exec=sh -c "/usr/bin/pkexec gparted"```

**Comment by palinek** [comment]
@luis-pereira i see (i was blind before)...

**Comment by paulolieuthier** [comment]
@palinek pull @luis-pereira's commits to your branch so it can be merged.

**Comment by palinek** [comment]
@paulolieuthier done

**Comment by luis-pereira** [comment]
@palinek Pls pull it again, sorry. I added some minor documentation and wrote an commit message.

**Comment by palinek** [comment]
@luis-pereira done... should this be landed?

**Comment by luis-pereira** [comment]
@palinek Yes, GTM.

**Pull request merged**
