### PR TITLE
Icon follow color

### PR DESCRIPTION
**Pull request by palinek**
@tsujan please, consider this one as follow-up of #119 (my implementation of FollowColorScheme and (big?) optimization of pixmap generation)

### CODE REVIEW

**Comment by tsujan** [comment]
Interesting! At the first glance, this is very similar to one of my three solutions. But I'll read your code tomorrow, hoping that its readings are less that of https://github.com/lxde/libqtxdg/pull/120.

**Comment by tsujan** [comment]
@palinek 
Before going to bed, I was so curious that I tested the branch `icon_follow_color`. I'm afraid it doesn't work. I haven't read the code yet (its general structure is like what I tested before though), so I have no clue about the cause.

Screenshot with this PR:



And this one with https://github.com/lxde/libqtxdg/pull/120:

**Comment by palinek** [comment]
heh... maybe I've found the reason... the problem can be in the used stylesheet in the "generated" svg, because it is dependent on the QIcon::Mode...

**Comment by tsujan** [comment]
Yes, it was `QIcon::Mode` that should be considered.

This is the best solution so far because both ordinary and selected icons are remembered and the readings are minimal. Well done!

You could just make the code tidier. For example, `m_followsColorTheme` and its related functions seem redundant in `XdgIconLoader`, unless you've thought of a fututre use for them. "followsColorTheme" can be changed to "followsThemeColor" too.

Some KDE icons has extra schemes. We could decide about them later. This is readey for merge after some cleanup and, perhaps, some tests by others. However, I emphasize the importance of patching Panel and other LXQt components that accept stylesheets before merging this. I'm sure you know why now.

**Comment by tsujan** [comment]
As for extra SVG schemes, it may be good to discuss them here later.

**Comment by palinek** [comment]
> For example, m_followsColorTheme and its related functions seem redundant in XdgIconLoader, unless you've thought of a fututre use for them.

That flag is to make XdgIconLoader "configurable"... it may be used standalone in other projects that don't want/need this processing. And I also intend to make this configurable in LXQt, so user can choose if she/he needs better performance or nice look.

**Comment by tsujan** [comment]
Although I don't think we'll need it for better performance (no one uses Commodore 64 nowadays), we might be able to make Panel (and...) use it automatically and ignore SVG stylesheets *when it has its own stylesheet*. In that way, the user could choose an icon set suitable for Panel (for example, dark breeze for dark panels) while other apps will show the correct colors of symbolic icons.

**Comment by tsujan** [comment]
The following lines in `Kvantum.cpp`, if I correctly remember:
````
  if (enoughContrast(txtCol, QApplication::palette().color(QPalette::WindowText)))
    icnMode = QIcon::Selected;
````

**Comment by palinek** [comment]
Reworded & squashed ... now this should be ready to merge.

@luis-pereira can you have a look on this?

**Comment by palinek** [comment]
> we might be able to make Panel (and...) use it automatically and ignore SVG stylesheets when it has its own stylesheet.

Maybe a dumb question (I'm lacking the knowledge in this area), but the style engine (kvantum, breeze...) is completely bypassed if there is an stylesheet attached for widget/application?

**Comment by tsujan** [comment]
> the style engine (kvantum, breeze...) is completely bypassed if there is an stylesheet attached for widget/application?

Not necessarily. It depends on the stylesheet. The style engine isn't consulted about those parameters that are set by the stylesheet. For example, if the stylesheet sets the border and background of a push button, `QStyle::drawControl(QStyle::CE_PushButtonBevel,option,painter,widget)` won't be called but `QStyle::drawControl(QStyle::CE_PushButtonLabel,option,painter,widget)` will be called and that could cause problems if a stylesheet is incomplete.

Here, the problem is that, for Panel, `qApp->palette()` gives the palette that's used by all apps, not the stylesheet colors. So, for example, `qApp->palette().windowText().color()` may not have enough contrast with the background color set by the stylesheet. Therefore, either the app palette should be changed or Panel should ignore SVG stylesheete.

**Comment by tsujan** [comment]
BTW, as I mentioned earlier, we might have to consider other SVG stylesheets too. So, I don't think this is ready for a merge yet.

See `window-close.svg` in the "16" folder of breeze! It uses `ColorScheme-NegativeText`, which has meaning only for KDE. It's better to include such cases too. There isn't any other case as far as I know.

**Comment by tsujan** [comment]
I add this in case you complain about exceptions (since I won't be at my computer today).

Styling codes can't be straightforward. Exceptions should be taken into account by them (in a systematic way). That's why many good developers make ridiculous GUI's.

KDE's way of dealing with symbolic icons isn't so efficient either. They've acknowledged only the Breeze style (while QtCurve is also in "projects.kde.org"). I'm afraid this isn't unlike the attitude of Gnome devs. We could go with them as far as their code isn't too Gnomish.

**Comment by palinek** [comment]
> See window-close.svg in the "16" folder of breeze! It uses ColorScheme-NegativeText, which has meaning only for KDE. It's better to include such cases too. There isn't any other case as far as I know.

Why don't we include all the classes as in [KDE iconloader](https://github.com/KDE/kiconthemes/blob/master/src/kiconloader.cpp#L77)?

**Comment by tsujan** [comment]
> Why don't we include all the classes as in KDE iconloader?

You could try to add all of them. I was selective because most of them weren't needed by LXQt.

**Comment by agaida** [comment]
blocked by #116 for now - patch dosn't apply clean so i could not build with it unchanged

**Comment by tsujan** [comment]
> blocked by #116 for now

Whichever is merged sooner, the other one should be rebased. I use both without problem.

**Comment by agaida** [comment]
right - but we should give @luis-pereira time to catch up

**Comment by tsujan** [comment]
Of course. No haste.

**Comment by luis-pereira** [comment]
It's fine. My only concern is performance. Does somebody have an idea on how it performs ? Are there any numbers ?

**Comment by agaida** [comment]
@palinek - please rebase

**Comment by palinek** [comment]
rebased

**Pull request merged**
